#!/usr/bin/env python3
"""
wrd_deobfuscator.py

Best-effort static deobfuscator for Lua/Luau files produced by the WeAreDevs.net
obfuscator family.

What it does:
  1. Decodes Lua decimal escapes such as \083\120\089.
  2. Extracts the constant string table usually named P.
  3. Replays the table-range reversals used by WRD.
  4. Reconstructs the custom base64 alphabet/map from the obfuscated decoder.
  5. Decodes the full string pool.
  6. Produces a partially cleaned Lua file with X(number) constant lookups replaced
     by readable Lua string/number literals.
  7. Writes a string dump for manual reconstruction of VM-obfuscated scripts.

Limitations:
  - WRD often uses a custom VM/state-machine. Static string decoding alone cannot
    recover lost original variable names or exactly undo the VM dispatcher.
  - This script does NOT execute the target script.

Usage:
  python3 wrd_deobfuscator.py input.lua -o output_dir

Example:
  python3 wrd_deobfuscator.py getdwo.lua -o deob_out
"""
from __future__ import annotations

import argparse
import ast
import os
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple


# ----------------------------- safe expression eval -----------------------------

_ALLOWED_AST = (
    ast.Expression,
    ast.UnaryOp,
    ast.BinOp,
    ast.Constant,
    ast.Add,
    ast.Sub,
    ast.Mult,
    ast.Div,
    ast.FloorDiv,
    ast.Mod,
    ast.Pow,
    ast.USub,
    ast.UAdd,
    ast.Load,
)


def safe_eval_int(expr: str) -> int:
    """Evaluate simple integer arithmetic generated by Lua obfuscators."""
    expr = expr.strip()
    # Lua and Python use the same operators here except Lua // is rare in these files.
    tree = ast.parse(expr, mode="eval")
    for node in ast.walk(tree):
        if not isinstance(node, _ALLOWED_AST):
            raise ValueError(f"unsafe expression: {expr!r}, node={type(node).__name__}")
    val = eval(compile(tree, "<expr>", "eval"), {"__builtins__": {}}, {})
    return int(val)


# ----------------------------- Lua string handling ------------------------------

_SIMPLE_ESCAPES = {
    "a": "\a",
    "b": "\b",
    "f": "\f",
    "n": "\n",
    "r": "\r",
    "t": "\t",
    "v": "\v",
    "\\": "\\",
    '"': '"',
    "'": "'",
}


def decode_lua_escapes(s: str) -> str:
    """Decode the content of a Lua short string literal."""
    out: List[str] = []
    i = 0
    n = len(s)
    while i < n:
        ch = s[i]
        if ch != "\\":
            out.append(ch)
            i += 1
            continue
        i += 1
        if i >= n:
            out.append("\\")
            break
        esc = s[i]
        if esc in _SIMPLE_ESCAPES:
            out.append(_SIMPLE_ESCAPES[esc])
            i += 1
        elif esc == "x" and i + 2 < n:
            hx = s[i + 1 : i + 3]
            try:
                out.append(chr(int(hx, 16)))
                i += 3
            except ValueError:
                out.append("\\x")
                i += 1
        elif esc.isdigit():
            # Lua decimal escapes consume up to 3 decimal digits.
            j = i
            while j < n and j < i + 3 and s[j].isdigit():
                j += 1
            out.append(chr(int(s[i:j], 10) & 0xFF))
            i = j
        elif esc == "z":
            # Lua \z skips following whitespace.
            i += 1
            while i < n and s[i] in " \t\r\n\v\f":
                i += 1
        elif esc == "\n":
            i += 1
        elif esc == "\r":
            i += 1
            if i < n and s[i] == "\n":
                i += 1
        else:
            out.append(esc)
            i += 1
    return "".join(out)


def lua_quote(s: str) -> str:
    """Return a safe Lua double-quoted literal."""
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif 32 <= o <= 126:
            out.append(ch)
        else:
            out.append(f"\\{o:03d}")
    out.append('"')
    return "".join(out)


def decode_all_short_string_escapes(src: str) -> str:
    """Decode escapes in all Lua short string literals while preserving quotes."""
    out: List[str] = []
    i = 0
    n = len(src)
    while i < n:
        ch = src[i]
        if ch not in "'\"":
            out.append(ch)
            i += 1
            continue
        quote = ch
        j = i + 1
        content: List[str] = []
        escaped = False
        while j < n:
            c = src[j]
            if escaped:
                content.append("\\" + c)
                escaped = False
                j += 1
            elif c == "\\":
                escaped = True
                j += 1
            elif c == quote:
                break
            else:
                content.append(c)
                j += 1
        if j >= n:
            out.append(src[i:])
            break
        decoded = decode_lua_escapes("".join(content))
        out.append(lua_quote(decoded))
        i = j + 1
    return "".join(out)


# ----------------------------- Source scanning ----------------------------------


def find_matching_brace(src: str, open_pos: int) -> int:
    assert src[open_pos] == "{"
    depth = 0
    i = open_pos
    n = len(src)
    quote: Optional[str] = None
    while i < n:
        ch = src[i]
        if quote:
            if ch == "\\":
                i += 2
                continue
            if ch == quote:
                quote = None
            i += 1
            continue
        if ch in "'\"":
            quote = ch
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    raise ValueError("matching brace not found")


def extract_short_strings(chunk: str) -> List[str]:
    vals: List[str] = []
    i = 0
    n = len(chunk)
    while i < n:
        if chunk[i] not in "'\"":
            i += 1
            continue
        quote = chunk[i]
        j = i + 1
        content: List[str] = []
        escaped = False
        while j < n:
            c = chunk[j]
            if escaped:
                content.append("\\" + c)
                escaped = False
                j += 1
            elif c == "\\":
                escaped = True
                j += 1
            elif c == quote:
                break
            else:
                content.append(c)
                j += 1
        if j >= n:
            break
        vals.append(decode_lua_escapes("".join(content)))
        i = j + 1
    return vals


def extract_p_table(src: str) -> Tuple[List[str], Tuple[int, int]]:
    m = re.search(r"\blocal\s+P\s*=\s*\{", src)
    if not m:
        raise ValueError("could not find `local P={...}` string table")
    open_pos = src.find("{", m.start())
    close_pos = find_matching_brace(src, open_pos)
    table_chunk = src[open_pos + 1 : close_pos]
    return extract_short_strings(table_chunk), (open_pos, close_pos)


def parse_range_reversals(src: str, after_pos: int) -> List[Tuple[int, int]]:
    """Parse ipairs({{a;b},{c;d}}) range reversal tuples, if present."""
    window = src[after_pos : after_pos + 2500]
    m = re.search(r"ipairs\s*\(\s*(\{\s*\{.*?\}\s*\})\s*\)", window, re.S)
    if not m:
        return []
    block = m.group(1)
    pairs: List[Tuple[int, int]] = []
    for a, b in re.findall(r"\{\s*([^;{},]+)\s*;\s*([^;{},]+)\s*\}", block):
        try:
            pairs.append((safe_eval_int(a), safe_eval_int(b)))
        except Exception:
            pass
    return pairs


def apply_reversals(arr: List[str], ranges: List[Tuple[int, int]]) -> None:
    # Lua indexes are 1-based and inclusive.
    for lo, hi in ranges:
        lo -= 1
        hi -= 1
        while lo < hi and 0 <= lo < len(arr) and 0 <= hi < len(arr):
            arr[lo], arr[hi] = arr[hi], arr[lo]
            lo += 1
            hi -= 1


def extract_decode_map(src: str) -> Dict[str, int]:
    """Extract the custom base64 char->value table named i={...}."""
    m = re.search(r"\blocal\s+i\s*=\s*\{", src)
    if not m:
        raise ValueError("could not find decoder map `local i={...}`")
    open_pos = src.find("{", m.start())
    close_pos = find_matching_brace(src, open_pos)
    chunk = src[open_pos + 1 : close_pos]

    result: Dict[str, int] = {}
    # entries are either ["\054"]=expr or v=expr
    token_re = re.compile(
        r"(?:\[\s*(['\"])((?:\\.|(?!\1).)*)\1\s*\]|([A-Za-z_][A-Za-z0-9_]*))\s*=\s*([^,;{}]+)",
        re.S,
    )
    for qm, quoted_key, bare_key, expr in token_re.findall(chunk):
        key = decode_lua_escapes(quoted_key) if qm else bare_key
        if len(key) != 1:
            continue
        try:
            result[key] = safe_eval_int(expr)
        except Exception:
            continue
    if len(result) < 60:
        raise ValueError(f"decoder map looked incomplete: only {len(result)} entries")
    return result


# ----------------------------- WRD base64 decoder -------------------------------


def wrd_b64_decode(s: str, table: Dict[str, int]) -> str:
    out = bytearray()
    acc = 0
    count = 0
    i = 0
    n = len(s)
    while i < n:
        ch = s[i]
        val = table.get(ch)
        if val is not None:
            acc += val * (64 ** (3 - count))
            count += 1
            if count == 4:
                out.extend(((acc // 65536) & 0xFF, ((acc % 65536) // 256) & 0xFF, acc & 0xFF))
                acc = 0
                count = 0
        elif ch == "=":
            out.append((acc // 65536) & 0xFF)
            if i >= n - 1 or s[i + 1] != "=":
                out.append(((acc % 65536) // 256) & 0xFF)
            break
        i += 1
    return out.decode("latin1")


def decode_pool(pool: List[str], table: Dict[str, int]) -> List[str]:
    decoded: List[str] = []
    for item in pool:
        try:
            decoded.append(wrd_b64_decode(item, table))
        except Exception:
            decoded.append(item)
    return decoded


# ----------------------------- Lua cleanup --------------------------------------


def constant_index_from_expr(expr: str) -> Optional[int]:
    """
    Try to resolve X(expr) where X returns P[expr - offset].
    In this WRD variant, function X(X)return P[X-61536]end.
    """
    try:
        return safe_eval_int(expr)
    except Exception:
        return None


def find_x_offset(src: str) -> int:
    m = re.search(r"local\s+function\s+X\s*\(\s*X\s*\)\s*return\s+P\s*\[\s*X\s*-\s*\((.*?)\)\s*\]", src, re.S)
    if m:
        return safe_eval_int(m.group(1))
    # Common fallback from this sample: X(n) = P[n - 61536]
    return 61536


def replace_x_calls(src: str, decoded_pool: List[str], offset: int) -> str:
    """Replace simple X(arithmetic) calls with literal strings."""
    pattern = re.compile(r"\bX\s*\(\s*([^()]*?(?:[-+*/%]\s*[^()]*)?)\s*\)")

    def repl(m: re.Match) -> str:
        expr = m.group(1)
        idx = constant_index_from_expr(expr)
        if idx is None:
            return m.group(0)
        pool_idx = idx - offset
        if 1 <= pool_idx <= len(decoded_pool):
            return lua_quote(decoded_pool[pool_idx - 1])
        return m.group(0)

    return pattern.sub(repl, src)


def remove_first_wrd_header(src: str) -> str:
    return re.sub(r"^\s*--\[\[\s*v[\s\S]*?wearedevs\.net/obfuscator\s*\]\]\s*", "", src, count=1, flags=re.I)


# ----------------------------- Main ---------------------------------------------


def deobfuscate(input_path: Path, out_dir: Path) -> None:
    raw = input_path.read_text(encoding="latin1")
    out_dir.mkdir(parents=True, exist_ok=True)

    stage1 = decode_all_short_string_escapes(raw)
    (out_dir / "stage1_escapes_decoded.lua").write_text(stage1, encoding="latin1")

    pool, (p_open, p_close) = extract_p_table(raw)
    ranges = parse_range_reversals(raw, p_close)
    if ranges:
        apply_reversals(pool, ranges)

    decode_map = extract_decode_map(raw)
    decoded_pool = decode_pool(pool, decode_map)

    # Dump all strings. Use repr-style bytes for nonprintable strings.
    lines = []
    for i, val in enumerate(decoded_pool, 1):
        printable = lua_quote(val)
        lines.append(f"[{i:04d}] {printable}")
    (out_dir / "decoded_strings.txt").write_text("\n".join(lines) + "\n", encoding="latin1")

    offset = find_x_offset(raw)
    stage2 = replace_x_calls(stage1, decoded_pool, offset)
    stage2 = remove_first_wrd_header(stage2)
    (out_dir / "stage2_constants_inlined.lua").write_text(stage2, encoding="latin1")

    # Also create a Lua module containing the decoded pool for manual analysis.
    module_lines = ["-- Decoded WRD string pool", "return {"]
    for val in decoded_pool:
        module_lines.append("    " + lua_quote(val) + ",")
    module_lines.append("}\n")
    (out_dir / "decoded_pool.lua").write_text("\n".join(module_lines), encoding="latin1")

    report = f"""WRD deobfuscation report
Input: {input_path}
String constants extracted: {len(pool)}
Range reversals found: {ranges or 'none'}
Decoder alphabet entries: {len(decode_map)}
X() offset: {offset}

Outputs:
- stage1_escapes_decoded.lua      Lua decimal escapes decoded
- decoded_strings.txt             decoded string pool
- decoded_pool.lua                decoded string pool as a Lua table
- stage2_constants_inlined.lua    readable constants inlined where statically resolvable

Note: If the result still has a giant numeric dispatcher, the file is VM-obfuscated.
Exact original source cannot be recovered statically, but these outputs expose the
string pool and most readable API names needed for manual reconstruction.
"""
    (out_dir / "REPORT.txt").write_text(report, encoding="utf-8")
    print(report)


def main() -> None:
    ap = argparse.ArgumentParser(description="Best-effort WeAreDevs Lua/Luau deobfuscator")
    ap.add_argument("input", help="input obfuscated .lua file")
    ap.add_argument("-o", "--out", default="deob_out", help="output directory")
    args = ap.parse_args()
    deobfuscate(Path(args.input), Path(args.out))


if __name__ == "__main__":
    main()
